name: Build DEB Package

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup environment
      run: |
        # Создаем рабочую папку
        WORKSPACE="$HOME/workspace"
        mkdir -p $WORKSPACE
        cd $WORKSPACE
        
    - name: Get source code
      run: |
        cd $HOME/workspace
        git clone https://github.com/${{ github.repository }} source
        cd source
        git checkout ${{ github.sha }}
        
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y build-essential
        
    - name: Build binary
      run: |
        cd $HOME/workspace/source
        gcc -static -O2 -Wall -o reverse-shell src/main.c src/reverse_shell.c src/templates.c
        
    - name: Create DEB package
      run: |
        cd $HOME/workspace
        mkdir -p pkg/usr/bin
        mkdir -p pkg/DEBIAN
        
        cp source/reverse-shell pkg/usr/bin/
        
        cat > pkg/DEBIAN/control << EOF
Package: reverse-shell-generator
Version: 1.0-${{ github.run_number }}
Section: net
Priority: optional
Architecture: amd64
Depends: netcat, xclip
Maintainer: ${{ github.actor }}
Description: Reverse Shell Generator Advanced penetration testing tool with multiple shell types.
 EOF
        
        dpkg-deb --build pkg reverse-shell-generator.deb
        
    - name: Verify package
      run: |
        cd $HOME/workspace
        echo "=== Package created ==="
        ls -la *.deb
        echo "=== Package info ==="
        dpkg -I reverse-shell-generator.deb || true