name: Simple Build and Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout and build
      run: |
        git clone https://github.com/${{ github.repository }} .
        gcc -static -O2 -Wall -o reverse-shell src/main.c src/reverse_shell.c src/templates.c
        
        VERSION=${GITHUB_REF#refs/tags/v}
        mkdir -p pkg/usr/bin pkg/DEBIAN
        cp reverse-shell pkg/usr/bin/
        
        cat > pkg/DEBIAN/control << EOF
        Package: reverse-shell-generator
        Version: $VERSION
        Section: net
        Priority: optional
        Architecture: amd64
        Depends: netcat, xclip
        Maintainer: Auto Builder
        Description: Reverse Shell Generator
        EOF
        
        dpkg-deb --build pkg reverse-shell-generator_${VERSION}_amd64.deb
        
    - name: Create Release
      run: |
        TAG=${{ github.ref_name }}
        VERSION=${TAG#v}
        
        # Простой JSON без сложного форматирования
        JSON_DATA="{\"tag_name\":\"$TAG\",\"name\":\"Version $VERSION\",\"body\":\"Reverse Shell Generator $VERSION\",\"draft\":false,\"prerelease\":false}"
        
        echo "JSON data: $JSON_DATA"
        
        curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${{ github.repository }}/releases" \
          -d "$JSON_DATA"